defaults:
  - /api_params/openai_base@_here_
#engine: "davinci-codex"
engine: "code-davinci-001"
temperature: 0.0
max_tokens: 1024
top_p: 1.0
# frequency_penalty: 0.2
# presence_penalty: 0.1
frequency_penalty: 0.2
presence_penalty: 0.0
stop:
  - "\n\n\n"
# stop:
  # - "\"\"\""
  # - "\n\n\n"