defaults:
  - /generation_params/summary_base@_here_
header: The following paragraphs contain computer science jargon. Rewrite them using simple words.
split_file: prompt_split.txt
category_file: prompt_category.yaml
num_few_shot: 5
ignore_intro: True
summary_types: [expert]
summary_prefix: "Simple: "
original_prefix: "Jargon: "
few_shot_suffix: "\n\n"