header: ""
splitFile: prompt_split.txt
promptFile: prompt_category.yaml
numPrompts: 3
summaryType: expert
ignoreIntro: True
ignoreTrain: True
originalPrefix: ""
summaryPrefix: "tl;dr: "
fewShotSuffix: "\n\n"

apiParams:
    engine: "ada"
    temperature: 0.25
    max_tokens: 500
    top_p: 1.0
    frequency_penalty: 0.0
    presence_penalty: 0.0
    stop:
        - "\n\n"
