model: jumbo
header: The following paragraphs contain computer science jargon. Rewrite them using
  simple words.
promptFile: prompt.yaml
numPrompts: 3
summaryType: expert
apiParams:
  topP: 1.0
  maxTokens: 100
  numResults: 1
  temperature: 0.5
  topKReturn: 0
  stopSequences:
  - Jargon
  - '


    '
