token: YOUR-API-TOKEN-HERE 
model: large # should be large or jumbo
header: The following paragraphs contain computer science jargon. Rewrite them using simple words.
promptFile: prompt.yaml
numPrompts: 5
summaryType: expert

apiParams:
    topP: 1.0
    maxTokens: 10
    numResults: 1
    temperature: 0.0
    topKReturn: 0
    stopSequences:
        - Jargon
        - "\n\n"
