model: large # should be large or jumbo
header: The following paragraphs contain computer science jargon. Rewrite them using simple words.
splitFile: split.txt
promptFile: prompt.yaml
numPrompts: 5
pathToData: "../data"
summaryType: expert
ignoreIntro: True
summaryPrefix: "Simple:"
originalPrefix: "Jargon:"
fewShotSuffix: "\n\n"

apiParams:
    topP: 1.0
    maxTokens: 200
    numResults: 1
    temperature: 0.5
    topKReturn: 0
    stopSequences:
        - Jargon
        - "\n\n"
