model: large # should be large or jumbo
header: ""
splitFile: split.txt
promptFile: prompt.yaml
numPrompts: 1
pathToData: "../data"
summaryType: expert
ignoreIntro: True
summaryPrefixStart: 'I have rephrased the programming question into simpler terms after removing jargon like this \n"""'
summaryPrefixEnd: '\n"""\n'
originalPrefixStart: 'I was given a computer science programming question like this \n"""\n'
originalPrefixEnd: '\n"""\n'
fewShotSuffix: "\n"

apiParams:
    engine: "ada"
    temperature: 0.25
    max_tokens: 500
    top_p: 1.0
    frequency_penalty: 0.0
    presence_penalty: 0.0
    stop:
        - "\"\"\""